# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: process_fakes
publish_to: none

# Required for workspace support.
environment:
  sdk: ^3.7.0-0

# This package is managed as part of the engine workspace.
resolution: workspace

dependencies:
  file: any
  meta: any
  path: any
  platform: any
  process: any

dependency_overrides:
  file:
    path: ../../../../third_party/dart/third_party/pkg/file/packages/file
  meta:
    path: ../../../../third_party/dart/pkg/meta
  path:
    path: ../../../../third_party/dart/third_party/pkg/path
  platform:
    path: ../../../third_party/pkg/platform
  process:
    path: ../../../third_party/pkg/process
